const Rover = require('../src/Rover')

test('when input "L" cardinal should spin to the 90 degrees cardinal anticlockwise ', () => {
    const rover = new Rover()
    rover.move('L')
    expect(rover.getPosition.heading).toBe("W")
    rover.move('L')
    expect(rover.getPosition.heading).toBe("S")
    rover.move('L')
    expect(rover.getPosition.heading).toBe("E")
    rover.move('L')
    expect(rover.getPosition.heading).toBe("N")
    rover.move('L')
    expect(rover.getPosition.heading).toBe("W")
})

test('when input "R" cardinal should spin to the 90 degrees cardinal anticlockwise ', () => {
    const rover = new Rover()
    rover.move('R')
    expect(rover.getPosition.heading).toBe("E")
    rover.move('R')
    expect(rover.getPosition.heading).toBe("S")
    rover.move('R')
    expect(rover.getPosition.heading).toBe("W")
    rover.move('R')
    expect(rover.getPosition.heading).toBe("N")
    rover.move('R')
    expect(rover.getPosition.heading).toBe("E")
})